### PR TITLE
Remove executables/popoolation

### PR DESCRIPTION
**Pull request by magicDGS**
The whole popoolation toolkit is linked into the executables, which is bad because it is only used for the `trim-fastq.pl`.

Because nowadays nobody uses the trim-fastq.pl, but ReadTools, I do not think that it should be bundled anymore into the repo.

Removing this executable is part of #7 and also deletes a lot of unused files (part of #6), but it makes easier things like #26

### CODE REVIEW

**Comment by magicDGS** [comment]
I think that you should have a look to this one for remove a bunch of unused files that makes even more difficult to cleanup the file structure.

**Comment by robmaz** [comment]
I am not sure this trim-fastq.pl script is currently unused. It appears to me that the --only-trim option in fact does use it.

**Comment by magicDGS** [comment]
The only place where it appears after checking in the repo is in `bin/cluster_trimming.pl` and `bin/cluster_trimming-1.pl`. But I guess that it is uploaded into the hadoop files if not provided by the user.

Thus, I will revert both trimming scripts in this branch (`trim-fastq.pl` and `trim-fastq_gz.pl`) and add a `README`to the popoolation folder indicating the origin of the files.

**Comment by robmaz** [comment]
They appear to use the "Test" and trim-fastq_gz.pl also the "Pileup" module. Tracking down these internal dependencies now seems like a bit of a waste, though, since we want to remove the whole dependency anyway. Maybe we should just leave it in for now?

**Comment by magicDGS** [comment]
True, it has wierd dependencies - I'll close for now, until we remove the trimming from the cluster. I just realize that if the user provides a custom trim script from popoolation, it requires that its folder is complete too, so it is again a bad idea to continue supporting that...

**Pull request closed without merging**
