### PR TITLE
Use by default picard.jar instead of old picard jars

### PR DESCRIPTION
**Pull request by magicDGS**
The _MergeSamFiles.jar_ and _SortSam.jar_ are really old picard tools (version where each tool was separated), and thus we should favor the _picard.jar_ instead. This PR tries to do it in the following way:

* Raise an error if the `--picard-jar` option is provided with the deprecated ones
* Log a warning if the _picard-jar_ is not used
* Remove the deprecated jars from the repository
* Use the variable with the arg dictionary script name in the `HadoopMapping.pm` instead of the raw _SortSam.jar_ to still support both arguments

Part of #38

### CODE REVIEW

**Comment by robmaz** [comment]
I know for a fact that some people are still using command lines with these old jars. And since they are so old, It may be difficult to even find them if they are removed from our repo.

Also, I would really like to finish the folder renaming before we start with the enhancements.

**Comment by magicDGS** [comment]
@robmaz - this is not removing the support of the old jars, but just from the repo and default to the picard.jar

If they are still using an old copy and it comes from the distmap binaries, we shouldn't encourage it; if they really want to use old copies, they should go to the picard repository and compile them by themselves. If they want to use the default, they should let distmap choose the most recent one (until it isn't distributed with distmap).

I agree with finish the folder renaming before this...so I can wait until now. But I wanted to open this PR for your information, and for further discuss some cleaning issues...

**Comment by magicDGS** [comment]
@robmaz - do you think that this is a good idea after all? I still believe that it is important to start removing this old files and default to the picard.jar instead (if this is affected, I will substitute it by the current version)

**Comment by magicDGS** [comment]
Yes, this is removing the `DONTUSE` jars, because it defaults now to the `picard.jar`; on the other hand, the default to a launcher script for Picard will be nice, but for another PR.

Finally, it will be cool that it also can default to a launcher script of gatk4, because they integrated all the Picard tools there too!

**Pull request merged**
